### ISSUE TITLE
Is this library active / maintained?

### ISSUE THREAD

**Issue by bradacina** [niv/websocket.nim#3]
Hi there, quick question before starting to use this lib. Is the maintainer still active on here? Are pull requests looked at?

**Comment by niv** [comment]
I'm here! :)

While my time doesn't allow me to work on this at the moment, I've not given up on it. And any PR of course will be looked at and helped to go in.

**Comment by bradacina** [comment]
Ah very nice to see you're here. Thank you for the quick reply.
