### ISSUE TITLE
Example client doesn't compile

### ISSUE THREAD

**Issue by gradha** [niv/websocket.nim#31]
The example at http://niv.github.io/websocket.nim/docs/0.1.1/websocket/client.html is missing a very important first line `import websocket/client`. After adding this line, Nim 0.18.0 still won't compile it:

```
/Users/gradha/.nimble/pkgs/websocket-0.2.1/websocket/shared.nim(87, 49) template/generic instantiation from here
/Users/gradha/.nimble/pkgs/websocket-0.2.1/websocket/shared.nim(130, 14) Error: type mismatch: got <byte> but expected 'int'
```

I see the git repository is at 0.2.3, so I tried with `#head` but then there is a missing symbol:

```
/Users/gradha/.nimble/pkgs/websocket-#head/websocket/client.nim(47, 30) template/generic instantiation from here
/Users/gradha/.nimble/pkgs/websocket-#head/websocket/client.nim(46, 23) Error: undeclared identifier: 'newContext'
```

**Comment by Araq** [comment]
Welcome back. Compiling with ``-d:ssl`` (soon the default) should fix that.

**Comment by dom96** [comment]
websockets really shouldn't depend on ssl.

**Comment by hlaaftana** [comment]
Docs are outdated, but the -d:ssl issue is fixed now
