### ISSUE TITLE
Sending protobuf data cause frontend javascript websocket failed: Invalid frame header

### ISSUE THREAD

**Issue by gogolxdong** [niv/websocket.nim#37]
readFile() of a protobuf data file sizes 152.6kb , sendText and sendBinary cause frontend javascript websocket failed: Invalid frame header.

**Comment by dom96** [comment]
I guess this is in general an issue with sending large amounts of data over the websocket?

**Comment by gogolxdong** [comment]
reduce to one item data and it remains. I think it's out of the protobuf binary data breaking the websocket header frame.

**Comment by gogolxdong** [comment]
For websocket frame format reference, https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

**Comment by hlaaftana** [comment]
This seems to work:

```nim
import websocket, uri, asyncdispatch

const site = "wss://echo.websocket.org:443/".parseUri
const data = char(0x08) & char(0x96) & char(0x01)

let ws = waitFor newAsyncWebsocketClient(site)
waitFor ws.sendBinary(data)
echo waitFor(ws.readData())
```

It might be a problem with the specific data, maybe you could try sending to echo.websocket.org with the faulty binary and seeing what happens.

**Comment by gogolxdong** [comment]
@dom96 Your guess is probably right, what is the limit of sending websocket data ?

**Comment by gogolxdong** [comment]
I tested the boundary is around 35 data items, sizes 12.2 KB.

**Comment by gogolxdong** [comment]
Do not test with echo.websocket.org which is also limited to 131k strings.

**Comment by hlaaftana** [comment]
Perhaps you could use `makeFrame` to see if the produced frame is valid?

**Comment by dom96** [comment]
There does indeed seem to be some bug when sending large amounts of data at once. Annoying thing is that I'm just seeing a socket closure when this happens, here is the JSON data I was trying to send. I'll try to reproduce it: https://gist.github.com/dom96/9dba05c10f2d22c1c3d49d5d78e5444e
