### ISSUE TITLE
Server stops running as the socket closed by remote peer, close code: 1001

### ISSUE THREAD

**Issue by gogolxdong** [niv/websocket.nim#38]
Using websocket in karax , client closes with every refreshing, so does the server. I think it's out of the single thread of async socket, will multi-threads help?

**Comment by hlaaftana** [comment]
What do you mean every refreshing? Do you mean when you refresh the page on which the karax client and JS websocket client is running on? If that's the case I think that's just how browsers behave, you could utilize cookies though I think.

**Comment by hlaaftana** [comment]
Fair enough, now if the client closes you get Close opcode and data you can turn into a close code and reason by using extractCodeData.
