### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by TensorTom** [niv/websocket.nim#41]
What is "A robust RNG for the client data masking?"

**Comment by hlaaftana** [comment]
Sorry for no response, I didn't know this issue existed.

The random module states

> Do not use this module for cryptographic purposes!

Even if masking is useless it's useful to provide the user with an option to mask their data. I suppose this doesn't imply the binary size should be huge though. I'll look into not needing the random module.

**Comment by hlaaftana** [comment]
Closing because you can use your own masking key
